name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 2

jobs:
  ####################
  # Linux / macOS
  ####################

  Unix:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          ubuntu-22.04-gcc,
          ubuntu-22.04-clang,
          macos-12-apple-clang,
          macos-12-llvm-clang
        ]
        config: [Release, Debug]
        include:
          - name: ubuntu-22.04-gcc
            os: ubuntu-22.04
            compiler: gcc

          - name: ubuntu-22.04-clang
            os: ubuntu-22.04
            compiler: clang

          - name: macos-12-apple-clang
            os: macos-12
            compiler: apple-clang

          - name: macos-12-llvm-clang
            os: macos-12
            compiler: llvm-clang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            if [ "${{ matrix.compiler }}" = "gcc" ]; then
              sudo apt-get install -y g++
              echo "CC=gcc" >> $GITHUB_ENV
              echo "CXX=g++" >> $GITHUB_ENV
            else
              sudo apt-get install -y clang
              echo "CC=clang" >> $GITHUB_ENV
              echo "CXX=clang++" >> $GITHUB_ENV
            fi
            sudo apt-get install ccache

      - name: Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
            brew install ccache
            if [ "${{ matrix.compiler }}" = "llvm-clang" ]; then
              echo "CC='$(brew --prefix llvm@15)/bin/clang'" >> $GITHUB_ENV
              echo "CXX='$(brew --prefix llvm@15)/bin/clang++'" >> $GITHUB_ENV
            fi

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ matrix.name }}-${{ matrix.config }}-cache

      - name: Prepare ccache
        run: |
          ccache --max-size=1.0G
          ccache -V && ccache --show-stats && ccache --zero-stats

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DUSE_SANITIZER=Thread

      - name: Build
        run: cd build; make -j2; ccache --show-stats

      - name: Tests (TBB Threads)
        run: cd build; ././tests/foo_tests "[tbb]"

      - name: Tests (STD Threads)
        run: cd build; ././tests/foo_tests "[std]"
