name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 1

jobs:
  ####################
  # Linux / macOS
  ####################

  Unix:
    name: ${{ matrix.os }} (${{ matrix.compiler }}, ${{ matrix.config }}, ${{ matrix.sanitizer }}Sanitizer)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        config: [RelwithDebInfo, Debug]
        compiler: [gcc, apple, llvm]
        sanitizer: ["Address", "Thread"]
        exclude:
          - os: macos-12
            sanitizer: "Thread"
          - os: macos-12
            compiler: gcc
          - os: ubuntu-22.04
            compiler: apple
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      # - name: Install Ninja
      #   uses: seanmiddleditch/gha-setup-ninja@master

      - name: Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update
            if [ "${{ matrix.compiler }}" = "gcc" ]; then
              sudo apt-get install -y g++
              echo "CC=gcc" >> $GITHUB_ENV
              echo "CXX=g++" >> $GITHUB_ENV
            else
              sudo apt-get install -y clang
              echo "CC=clang" >> $GITHUB_ENV
              echo "CXX=clang++" >> $GITHUB_ENV
            fi
            sudo apt-get install xorg-dev ccache

      - name: Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
            brew install ccache
            if [ "${{ matrix.compiler }}" = "llvm" ]; then
              brew install llvm@15
              echo "CC='$(brew --prefix llvm@15)/bin/clang'" >> $GITHUB_ENV
              echo "CXX='$(brew --prefix llvm@15)/bin/clang++'" >> $GITHUB_ENV
            fi

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ matrix.name }}-${{ matrix.config }}-cache

      - name: Prepare ccache
        run: |
          ccache --max-size=1.0G
          ccache -V && ccache --show-stats && ccache --zero-stats

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DUSE_EXPLICIT_INSTANTIATION=OFF \
            -DUSE_SANITIZER=${{ matrix.sanitizer }}

      - name: Build
        run: |
          cmake --build build -j 1
          ccache --show-stats

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Tests
        run: cd build; ctest --verbose -j ${{ steps.cpu-cores.outputs.count }}
